//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbMaterial
// {
//
//   float4 gDiffuseAlbedo;             // Offset:    0 Size:    16
//   float3 gFresnelR0;                 // Offset:   16 Size:    12
//   float gRoughness;                  // Offset:   28 Size:     4
//   float4x4 gMatTransform;            // Offset:   32 Size:    64 [unused]
//
// }
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64 [unused]
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//   float4 gAmbientLight;              // Offset:  432 Size:    16
//   float4 gFogColor;                  // Offset:  448 Size:    16 [unused]
//   float gFogStart;                   // Offset:  464 Size:     4 [unused]
//   float gFogRange;                   // Offset:  468 Size:     4 [unused]
//   float2 cbPerObjectPad2;            // Offset:  472 Size:     8 [unused]
//   
//   struct Light
//   {
//       
//       float3 Strength;               // Offset:  480
//       float FalloffStart;            // Offset:  492
//       float3 Direction;              // Offset:  496
//       float FalloffEnd;              // Offset:  508
//       float3 Position;               // Offset:  512
//       float SpotPower;               // Offset:  524
//
//   } gLights[16];                     // Offset:  480 Size:   768
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gsamPointWrap                     sampler      NA          NA             s0      1 
// gDiffuseMap                       texture  float4          2d             t0      1 
// cbMaterial                        cbuffer      NA          NA            cb1      1 
// cbPass                            cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
// TEXCOORD                 0   xy          3     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB1[2], immediateIndexed
dcl_constantbuffer CB2[41], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_output o0.xyzw
dcl_temps 13
dcl_indexableTemp x0[21], 4
//
// Initial variable locations:
//   v0.x <- pin.PosH.x; v0.y <- pin.PosH.y; v0.z <- pin.PosH.z; v0.w <- pin.PosH.w; 
//   v1.x <- pin.PosW.x; v1.y <- pin.PosW.y; v1.z <- pin.PosW.z; 
//   v2.x <- pin.NormalW.x; v2.y <- pin.NormalW.y; v2.z <- pin.NormalW.z; 
//   v3.x <- pin.TexC.x; v3.y <- pin.TexC.y; 
//   o0.x <- <PS return value>.x; o0.y <- <PS return value>.y; o0.z <- <PS return value>.z; o0.w <- <PS return value>.w
//
#line 105 "C:\Users\a\source\repos\3D_Game_D3D12\Source\BlendDemo\default.hlsl"
sample_indexable(texture2d)(float,float,float,float) r0.xyz, v3.xyxx, t0.xyzw, s0
mul r0.xyz, r0.xyzx, cb1[0].xyzx  // r0.x <- diffuseAlbedo.x; r0.y <- diffuseAlbedo.y; r0.z <- diffuseAlbedo.z

#line 111
dp3 r1.x, v2.xyzx, v2.xyzx
rsq r1.x, r1.x
mul r1.xyz, r1.xxxx, v2.xyzx  // r1.x <- pin.NormalW.x; r1.y <- pin.NormalW.y; r1.z <- pin.NormalW.z

#line 113
mov r2.xyz, -v1.xyzx
add r2.xyz, r2.xyzx, cb2[24].xyzx  // r2.x <- toEyeW.x; r2.y <- toEyeW.y; r2.z <- toEyeW.z

#line 114
dp3 r1.w, r2.xyzx, r2.xyzx
sqrt r1.w, r1.w  // r1.w <- distToEye

#line 115
div r2.xyz, r2.xyzx, r1.wwww

#line 117
mul r3.xyz, r0.xyzx, cb2[27].xyzx  // r3.x <- ambient.x; r3.y <- ambient.y; r3.z <- ambient.z

#line 119
mov r1.w, -cb1[1].w
add r4.w, r1.w, l(1.000000)  // r4.w <- shininess

#line 120
mov r0.xyz, r0.xyzx  // r0.x <- mat.DiffuseAlbedo.x; r0.y <- mat.DiffuseAlbedo.y; r0.z <- mat.DiffuseAlbedo.z
mov r0.w, cb1[1].x  // r0.w <- mat.FresnelR0.x
mov r4.yz, cb1[1].yyzy  // r4.y <- mat.FresnelR0.y; r4.z <- mat.FresnelR0.z
mov r4.w, r4.w  // r4.w <- mat.Shininess

#line 123
nop 
mov x0[0].xyz, cb2[30].xyzx
mov x0[2].xyz, cb2[31].xyzx
mov x0[4].xyz, cb2[32].xyzx
mov x0[6].xyz, cb2[33].xyzx
mov x0[8].xyz, cb2[34].xyzx
mov x0[10].xyz, cb2[35].xyzx
mov x0[12].xyz, cb2[36].xyzx
mov x0[14].xyz, cb2[37].xyzx
mov x0[16].xyz, cb2[38].xyzx
mov x0[18].xyz, cb2[39].xyzx
mov x0[20].xyz, cb2[40].xyzx
mov r0.xyzw, r0.xyzw
mov r4.yzw, r4.yyzw
mov r1.xyz, r1.xyzx
mov r2.xyz, r2.xyzx

#line 109 "C:\Users\a\source\repos\3D_Game_D3D12\Source\BlendDemo\LightingUtil.hlsl"
mov r5.xyz, l(0,0,0,0)  // r5.x <- result.x; r5.y <- result.y; r5.z <- result.z

#line 114
mov r1.w, l(0)  // r1.w <- i
mov r6.xyz, r5.xyzx  // r6.x <- result.x; r6.y <- result.y; r6.z <- result.z
mov r2.w, r1.w  // r2.w <- i
loop 
  ilt r3.w, r2.w, l(3)
  breakc_z r3.w

#line 116
  mov r3.w, l(1.000000)  // r3.w <- shadowFactor.x
  nop 
  imul null, r4.x, r2.w, l(6)
  mov r7.xyz, x0[r4.x + 0].xyzx
  mov r8.xyz, x0[r4.x + 2].xyzx
  mov r9.x, r0.w
  mov r9.yzw, r4.yyzw
  mov r10.xyz, r0.xyzx
  mov r11.xyz, r1.xyzx
  mov r12.xyz, r2.xyzx

#line 54
  mov r8.xyz, -r8.xyzx  // r8.x <- lightVec.x; r8.y <- lightVec.y; r8.z <- lightVec.z

#line 56
  dp3 r4.x, r8.xyzx, r11.xyzx
  max r4.x, r4.x, l(0.000000)  // r4.x <- ndotl

#line 57
  mul r7.xyz, r4.xxxx, r7.xyzx  // r7.x <- lightStrength.x; r7.y <- lightStrength.y; r7.z <- lightStrength.z

#line 59
  nop 
  mov r7.xyz, r7.xyzx
  mov r8.xyz, r8.xyzx
  mov r11.xyz, r11.xyzx
  mov r12.xyz, r12.xyzx
  mov r10.xyz, r10.xyzx
  mov r9.xyzw, r9.xyzw

#line 39
  mul r4.x, r9.w, l(256.000000)  // r4.x <- m

#line 40
  add r12.xyz, r8.xyzx, r12.xyzx
  dp3 r5.w, r12.xyzx, r12.xyzx
  rsq r5.w, r5.w
  mul r12.xyz, r5.wwww, r12.xyzx  // r12.x <- halfVec.x; r12.y <- halfVec.y; r12.z <- halfVec.z

#line 42
  add r5.w, r4.x, l(8.000000)
  dp3 r6.w, r12.xyzx, r11.xyzx
  max r6.w, r6.w, l(0.000000)
  log r6.w, r6.w
  mul r4.x, r4.x, r6.w
  exp r4.x, r4.x
  mul r4.x, r4.x, r5.w
  div r4.x, r4.x, l(8.000000)  // r4.x <- roughnessFactor

#line 43
  nop 
  mov r9.xyz, r9.xyzx
  mov r12.xyz, r12.xyzx
  mov r8.xyz, r8.xyzx

#line 29
  dp3 r5.w, r12.xyzx, r8.xyzx
  max r5.w, r5.w, l(0.000000)
  min r5.w, r5.w, l(1.000000)  // r5.w <- cosIncidentAngle

#line 31
  mov r5.w, -r5.w
  add r5.w, r5.w, l(1.000000)  // r5.w <- f0

#line 32
  mov r8.xyz, -r9.xyzx
  add r8.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  mul r6.w, r5.w, r5.w
  mul r6.w, r5.w, r6.w
  mul r6.w, r5.w, r6.w
  mul r5.w, r5.w, r6.w
  mul r8.xyz, r5.wwww, r8.xyzx
  add r8.xyz, r8.xyzx, r9.xyzx  // r8.x <- reflectPercent.x; r8.y <- reflectPercent.y; r8.z <- reflectPercent.z

#line 34
  mov r8.xyz, r8.xyzx  // r8.x <- <SchlickFresnel return value>.x; r8.y <- <SchlickFresnel return value>.y; r8.z <- <SchlickFresnel return value>.z

#line 43
  mov r8.xyz, r8.xyzx  // r8.x <- fresnelFactor.x; r8.y <- fresnelFactor.y; r8.z <- fresnelFactor.z

#line 45
  mul r8.xyz, r4.xxxx, r8.xyzx  // r8.x <- specAlbedo.x; r8.y <- specAlbedo.y; r8.z <- specAlbedo.z

#line 47
  add r9.xyz, r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  div r8.xyz, r8.xyzx, r9.xyzx

#line 49
  add r8.xyz, r8.xyzx, r10.xyzx
  mul r7.xyz, r7.xyzx, r8.xyzx  // r7.x <- <BlinnPhong return value>.x; r7.y <- <BlinnPhong return value>.y; r7.z <- <BlinnPhong return value>.z

#line 59
  mov r7.xyz, r7.xyzx  // r7.x <- <ComputeDirectionalLight return value>.x; r7.y <- <ComputeDirectionalLight return value>.y; r7.z <- <ComputeDirectionalLight return value>.z

#line 116
  mul r7.xyz, r3.wwww, r7.xyzx
  add r6.xyz, r6.xyzx, r7.xyzx

#line 117
  iadd r2.w, r2.w, l(1)
endloop 

#line 134
mov r6.xyz, r6.xyzx  // r6.x <- <ComputeLighting return value>.x; r6.y <- <ComputeLighting return value>.y; r6.z <- <ComputeLighting return value>.z

#line 123 "C:\Users\a\source\repos\3D_Game_D3D12\Source\BlendDemo\default.hlsl"
mov r6.xyz, r6.xyzx  // r6.x <- directLight.x; r6.y <- directLight.y; r6.z <- directLight.z

#line 126
add r0.xyz, r3.xyzx, r6.xyzx  // r0.x <- litColor.x; r0.y <- litColor.y; r0.z <- litColor.z

#line 133
mov r0.w, cb1[0].w  // r0.w <- litColor.w

#line 135
mov o0.xyz, r0.xyzx
mov o0.w, r0.w
ret 
// Approximately 110 instruction slots used
